package com.example.mtgassassin.utils

import com.example.mtgassassin.data.Player

val testPlayersList = mutableListOf(
    Player("Robin"),
    Player("Mickaël"),
    Player("Victor"),
    Player("Pierre"),
    Player("Numa"),
    Player("Alex"),
    Player("Robin"),
    Player("Mickaël"),
    Player("Victor"),
    Player("Pierre"),
    Player("Numa"),
    Player("Alex"),
    Player("Robin"),
    Player("Mickaël"),
    Player("Victor"),
    Player("Pierre"),
    Player("Numa"),
    Player("Alex"),
    Player("Robin"),
    Player("Mickaël"),
    Player("Victor"),
    Player("Pierre"),
    Player("Numa"),
    Player("Alex"),
    Player("Robin"),
    Player("Mickaël"),
    Player("Victor"),
    Player("Pierre"),
    Player("Numa"),
    Player("Alex"),
)